name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            sdk: 'v3.0.0-alpha.2'
            cli: 'v3.0.0-beta.1'
            combine: true
            target: ''

        # Add other configurations for different platforms if needed

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2

      # Clone CustomKeybindsTest repository
      - name: Clone CustomKeybindsTest
        run: git clone https://github.com/InfernoWolf19/CustomKeybindsTest.git

      # Build CustomKeybindsTest
      - name: Build CustomKeybindsTest
        run: |
          cd CustomKeybindsTest
          mkdir build
          cd build
          cmake ..
          cmake --build .

      # Build ClickBetweenFrames
      - name: Build ClickBetweenFrames
        run: |
          cd ..
          mkdir build_ClickBetweenFrames
          cd build_ClickBetweenFrames
          cmake ..
          cmake --build .

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Build Output
          path: ${{ github.workspace }}/build_ClickBetweenFrames

      - uses: actions/upload-artifact@v2
        with:
          name: Packaged Build
          path: ${{ github.workspace }}/build_ClickBetweenFrames
